// Mocks generated by Mockito 5.4.6 from annotations
// in kowhai/test/services/audio_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:kowhai/models/audiobook.dart' as _i7;
import 'package:kowhai/models/availability_filter_state.dart' as _i8;
import 'package:kowhai/models/bookmark.dart' as _i3;
import 'package:kowhai/services/position_service.dart' as _i5;
import 'package:kowhai/services/preferences_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBookmark_1 extends _i1.SmartFake implements _i3.Bookmark {
  _FakeBookmark_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsSnapshot_2 extends _i1.SmartFake
    implements _i4.SettingsSnapshot {
  _FakeSettingsSnapshot_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PositionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPositionService extends _i1.Mock implements _i5.PositionService {
  MockPositionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get databaseForTesting => (super.noSuchMethod(
        Invocation.getter(#databaseForTesting),
        returnValue: _i6.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#databaseForTesting),
        )),
      ) as _i6.Future<_i2.Database>);

  @override
  _i6.Future<_i2.Database> get sharedDb => (super.noSuchMethod(
        Invocation.getter(#sharedDb),
        returnValue: _i6.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#sharedDb),
        )),
      ) as _i6.Future<_i2.Database>);

  @override
  _i6.Future<void> savePosition({
    required String? bookPath,
    required int? chapterIndex,
    required Duration? position,
    required int? globalPositionMs,
    required int? totalDurationMs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePosition,
          [],
          {
            #bookPath: bookPath,
            #chapterIndex: chapterIndex,
            #position: position,
            #globalPositionMs: globalPositionMs,
            #totalDurationMs: totalDurationMs,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<({int chapterIndex, Duration position})?> getPosition(
          String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [bookPath],
        ),
        returnValue:
            _i6.Future<({int chapterIndex, Duration position})?>.value(),
      ) as _i6.Future<({int chapterIndex, Duration position})?>);

  @override
  _i6.Future<void> setBookStatus(
    String? bookPath,
    _i7.BookStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBookStatus,
          [
            bookPath,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateBookStatus(
    String? bookPath,
    _i7.BookStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookStatus,
          [
            bookPath,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.BookStatus> getBookStatus(String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookStatus,
          [bookPath],
        ),
        returnValue:
            _i6.Future<_i7.BookStatus>.value(_i7.BookStatus.notStarted),
      ) as _i6.Future<_i7.BookStatus>);

  @override
  _i6.Future<Map<String, _i7.BookStatus>> getAllStatuses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllStatuses,
          [],
        ),
        returnValue: _i6.Future<Map<String, _i7.BookStatus>>.value(
            <String, _i7.BookStatus>{}),
      ) as _i6.Future<Map<String, _i7.BookStatus>>);

  @override
  _i6.Future<_i3.Bookmark> addBookmark(_i3.Bookmark? bookmark) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBookmark,
          [bookmark],
        ),
        returnValue: _i6.Future<_i3.Bookmark>.value(_FakeBookmark_1(
          this,
          Invocation.method(
            #addBookmark,
            [bookmark],
          ),
        )),
      ) as _i6.Future<_i3.Bookmark>);

  @override
  _i6.Future<List<_i3.Bookmark>> getBookmarks(String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarks,
          [bookPath],
        ),
        returnValue: _i6.Future<List<_i3.Bookmark>>.value(<_i3.Bookmark>[]),
      ) as _i6.Future<List<_i3.Bookmark>>);

  @override
  _i6.Future<void> deleteBookmark(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBookmark,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateBookmark(
    int? id, {
    required String? label,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookmark,
          [id],
          {
            #label: label,
            #notes: notes,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getLastPlayedBookPath() => (super.noSuchMethod(
        Invocation.method(
          #getLastPlayedBookPath,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<
      List<
          ({
            String bookPath,
            int globalPositionMs,
            int totalDurationMs,
            int updatedAt
          })>> getAllPositions() => (super.noSuchMethod(
        Invocation.method(
          #getAllPositions,
          [],
        ),
        returnValue: _i6.Future<
            List<
                ({
                  String bookPath,
                  int globalPositionMs,
                  int totalDurationMs,
                  int updatedAt
                })>>.value(<({
          String bookPath,
          int globalPositionMs,
          int totalDurationMs,
          int updatedAt
        })>[]),
      ) as _i6.Future<
          List<
              ({
                String bookPath,
                int globalPositionMs,
                int totalDurationMs,
                int updatedAt
              })>>);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i4.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.SettingsSnapshot> getSettingsSnapshot() => (super.noSuchMethod(
        Invocation.method(
          #getSettingsSnapshot,
          [],
        ),
        returnValue:
            _i6.Future<_i4.SettingsSnapshot>.value(_FakeSettingsSnapshot_2(
          this,
          Invocation.method(
            #getSettingsSnapshot,
            [],
          ),
        )),
      ) as _i6.Future<_i4.SettingsSnapshot>);

  @override
  _i6.Future<String?> getLibraryPath() => (super.noSuchMethod(
        Invocation.method(
          #getLibraryPath,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> setLibraryPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #setLibraryPath,
          [path],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearLibraryPath() => (super.noSuchMethod(
        Invocation.method(
          #clearLibraryPath,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool?> getAnalyticsConsent() => (super.noSuchMethod(
        Invocation.method(
          #getAnalyticsConsent,
          [],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<void> setAnalyticsConsent(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticsConsent,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> setThemeMode(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> getMetadataEnrichment() => (super.noSuchMethod(
        Invocation.method(
          #getMetadataEnrichment,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setMetadataEnrichment(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setMetadataEnrichment,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> getAutoRewind() => (super.noSuchMethod(
        Invocation.method(
          #getAutoRewind,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setAutoRewind(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoRewind,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> getSkipInterval() => (super.noSuchMethod(
        Invocation.method(
          #getSkipInterval,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> setSkipInterval(int? seconds) => (super.noSuchMethod(
        Invocation.method(
          #setSkipInterval,
          [seconds],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getLibrarySort() => (super.noSuchMethod(
        Invocation.method(
          #getLibrarySort,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> setLibrarySort(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setLibrarySort,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<({String id, bool isShared, String name})?> getDriveRootFolder() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriveRootFolder,
          [],
        ),
        returnValue:
            _i6.Future<({String id, bool isShared, String name})?>.value(),
      ) as _i6.Future<({String id, bool isShared, String name})?>);

  @override
  _i6.Future<void> setDriveRootFolder(
    String? id,
    String? name, {
    bool? isShared = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDriveRootFolder,
          [
            id,
            name,
          ],
          {#isShared: isShared},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearDriveRootFolder() => (super.noSuchMethod(
        Invocation.method(
          #clearDriveRootFolder,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> getRemoveWhenFinished() => (super.noSuchMethod(
        Invocation.method(
          #getRemoveWhenFinished,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setRemoveWhenFinished(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setRemoveWhenFinished,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> getRefreshOnStartup() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshOnStartup,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setRefreshOnStartup(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setRefreshOnStartup,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> getDriveProgressSync() => (super.noSuchMethod(
        Invocation.method(
          #getDriveProgressSync,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setDriveProgressSync(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDriveProgressSync,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<({String id, String name})?> getDriveBackupFolder() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriveBackupFolder,
          [],
        ),
        returnValue: _i6.Future<({String id, String name})?>.value(),
      ) as _i6.Future<({String id, String name})?>);

  @override
  _i6.Future<void> setDriveBackupFolder(
    String? id,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDriveBackupFolder,
          [
            id,
            name,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearDriveBackupFolder() => (super.noSuchMethod(
        Invocation.method(
          #clearDriveBackupFolder,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i8.AvailabilityFilterState> getAvailabilityFilter() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailabilityFilter,
          [],
        ),
        returnValue: _i6.Future<_i8.AvailabilityFilterState>.value(
            _i8.AvailabilityFilterState.all),
      ) as _i6.Future<_i8.AvailabilityFilterState>);

  @override
  _i6.Future<void> setAvailabilityFilter(_i8.AvailabilityFilterState? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAvailabilityFilter,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
