// Mocks generated by Mockito 5.4.6 from annotations
// in kowhai/test/screens/book_download_prompt_preservation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i17;

import 'package:flutter/foundation.dart' as _i2;
import 'package:kowhai/models/audiobook.dart' as _i9;
import 'package:kowhai/models/availability_filter_state.dart' as _i14;
import 'package:kowhai/models/bookmark.dart' as _i4;
import 'package:kowhai/services/drive_book_repository.dart' as _i10;
import 'package:kowhai/services/drive_download_manager.dart' as _i11;
import 'package:kowhai/services/drive_library_service.dart' as _i6;
import 'package:kowhai/services/enrichment_service.dart' as _i12;
import 'package:kowhai/services/position_service.dart' as _i13;
import 'package:kowhai/services/preferences_service.dart' as _i5;
import 'package:kowhai/services/scanner_service.dart' as _i15;
import 'package:kowhai/services/sleep_timer_controller.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_1<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBookmark_3 extends _i1.SmartFake implements _i4.Bookmark {
  _FakeBookmark_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsSnapshot_4 extends _i1.SmartFake
    implements _i5.SettingsSnapshot {
  _FakeSettingsSnapshot_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DriveLibraryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveLibraryService extends _i1.Mock
    implements _i6.DriveLibraryService {
  MockDriveLibraryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> stagingDir(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #stagingDir,
          [folderId],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #stagingDir,
            [folderId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> bookDir(
    String? folderId, {
    String? folderName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookDir,
          [folderId],
          {#folderName: folderName},
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #bookDir,
            [folderId],
            {#folderName: folderName},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<Set<String>> driveBookDirs() => (super.noSuchMethod(
        Invocation.method(
          #driveBookDirs,
          [],
        ),
        returnValue: _i7.Future<Set<String>>.value(<String>{}),
      ) as _i7.Future<Set<String>>);

  @override
  _i7.Future<List<_i9.Audiobook>> loadDriveBooks() => (super.noSuchMethod(
        Invocation.method(
          #loadDriveBooks,
          [],
        ),
        returnValue: _i7.Future<List<_i9.Audiobook>>.value(<_i9.Audiobook>[]),
      ) as _i7.Future<List<_i9.Audiobook>>);

  @override
  _i7.Future<List<_i9.Audiobook>> rescanDrive(
          {void Function(String)? onProgress}) =>
      (super.noSuchMethod(
        Invocation.method(
          #rescanDrive,
          [],
          {#onProgress: onProgress},
        ),
        returnValue: _i7.Future<List<_i9.Audiobook>>.value(<_i9.Audiobook>[]),
      ) as _i7.Future<List<_i9.Audiobook>>);

  @override
  _i7.Future<void> removeUndownloadedBooks() => (super.noSuchMethod(
        Invocation.method(
          #removeUndownloadedBooks,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> startDownload(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #startDownload,
          [folderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i9.Audiobook?> promoteToLocal(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #promoteToLocal,
          [folderId],
        ),
        returnValue: _i7.Future<_i9.Audiobook?>.value(),
      ) as _i7.Future<_i9.Audiobook?>);

  @override
  _i7.Future<void> undownloadBook(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #undownloadBook,
          [folderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> totalSizeBytes(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #totalSizeBytes,
          [folderId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> deleteLocalFiles(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocalFiles,
          [folderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [DriveBookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveBookRepository extends _i1.Mock
    implements _i10.DriveBookRepository {
  MockDriveBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> upsertDriveBook(_i10.DriveBookRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertDriveBook,
          [record],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> upsertFile(_i10.DriveFileRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertFile,
          [record],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.DriveBookRecord>> getAllDriveBooks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDriveBooks,
          [],
        ),
        returnValue: _i7.Future<List<_i10.DriveBookRecord>>.value(
            <_i10.DriveBookRecord>[]),
      ) as _i7.Future<List<_i10.DriveBookRecord>>);

  @override
  _i7.Future<_i10.DriveBookRecord?> getDriveBook(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriveBook,
          [folderId],
        ),
        returnValue: _i7.Future<_i10.DriveBookRecord?>.value(),
      ) as _i7.Future<_i10.DriveBookRecord?>);

  @override
  _i7.Future<void> resetBookDownloads(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #resetBookDownloads,
          [folderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteDriveBook(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDriveBook,
          [folderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.DriveFileRecord>> getFilesForBook(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilesForBook,
          [folderId],
        ),
        returnValue: _i7.Future<List<_i10.DriveFileRecord>>.value(
            <_i10.DriveFileRecord>[]),
      ) as _i7.Future<List<_i10.DriveFileRecord>>);

  @override
  _i7.Future<void> updateFileState(
    String? folderId,
    int? fileIndex,
    _i10.DriveDownloadState? state, {
    String? localPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFileState,
          [
            folderId,
            fileIndex,
            state,
          ],
          {#localPath: localPath},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateFileLocalPath(
    String? folderId,
    int? fileIndex,
    String? localPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFileLocalPath,
          [
            folderId,
            fileIndex,
            localPath,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resetStaleDownloads() => (super.noSuchMethod(
        Invocation.method(
          #resetStaleDownloads,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [DriveDownloadManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveDownloadManager extends _i1.Mock
    implements _i11.DriveDownloadManager {
  MockDriveDownloadManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get retryDelay => (super.noSuchMethod(
        Invocation.getter(#retryDelay),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#retryDelay),
        ),
      ) as Duration);

  @override
  _i7.Stream<_i11.DriveDownloadEvent> get downloadEvents => (super.noSuchMethod(
        Invocation.getter(#downloadEvents),
        returnValue: _i7.Stream<_i11.DriveDownloadEvent>.empty(),
      ) as _i7.Stream<_i11.DriveDownloadEvent>);

  @override
  _i7.Future<void> resumeInterruptedDownloads() => (super.noSuchMethod(
        Invocation.method(
          #resumeInterruptedDownloads,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> enqueueAllFiles(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #enqueueAllFiles,
          [folderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancelDownload(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [folderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> downloadCover({
    required String? folderId,
    required String? coverFileId,
    required String? destDir,
    String? fileName = 'cover.jpg',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadCover,
          [],
          {
            #folderId: folderId,
            #coverFileId: coverFileId,
            #destDir: destDir,
            #fileName: fileName,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EnrichmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnrichmentService extends _i1.Mock implements _i12.EnrichmentService {
  MockEnrichmentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<({String bookPath, String coverPath})> get onCoverFetched =>
      (super.noSuchMethod(
        Invocation.getter(#onCoverFetched),
        returnValue: _i7.Stream<({String bookPath, String coverPath})>.empty(),
      ) as _i7.Stream<({String bookPath, String coverPath})>);

  @override
  _i2.ValueNotifier<Set<String>> get enrichingPaths => (super.noSuchMethod(
        Invocation.getter(#enrichingPaths),
        returnValue: _FakeValueNotifier_1<Set<String>>(
          this,
          Invocation.getter(#enrichingPaths),
        ),
      ) as _i2.ValueNotifier<Set<String>>);

  @override
  _i2.ValueNotifier<Set<String>> get failedPaths => (super.noSuchMethod(
        Invocation.getter(#failedPaths),
        returnValue: _FakeValueNotifier_1<Set<String>>(
          this,
          Invocation.getter(#failedPaths),
        ),
      ) as _i2.ValueNotifier<Set<String>>);

  @override
  _i7.Future<({String? coverPath, bool enriched, DateTime? lastAttempted})>
      getStatus(String? bookPath) => (super.noSuchMethod(
            Invocation.method(
              #getStatus,
              [bookPath],
            ),
            returnValue: _i7.Future<
                    ({
                      String? coverPath,
                      bool enriched,
                      DateTime? lastAttempted
                    })>.value(
                (coverPath: null, enriched: false, lastAttempted: null)),
          ) as _i7.Future<
              ({String? coverPath, bool enriched, DateTime? lastAttempted})>);

  @override
  _i7.Future<Map<String, String>> getAllEnrichedCovers() => (super.noSuchMethod(
        Invocation.method(
          #getAllEnrichedCovers,
          [],
        ),
        returnValue: _i7.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<void> enqueueBooks(List<_i9.Audiobook>? books) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueBooks,
          [books],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void cancel() => super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PositionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPositionService extends _i1.Mock implements _i13.PositionService {
  MockPositionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.Database> get databaseForTesting => (super.noSuchMethod(
        Invocation.getter(#databaseForTesting),
        returnValue: _i7.Future<_i3.Database>.value(_FakeDatabase_2(
          this,
          Invocation.getter(#databaseForTesting),
        )),
      ) as _i7.Future<_i3.Database>);

  @override
  _i7.Future<_i3.Database> get sharedDb => (super.noSuchMethod(
        Invocation.getter(#sharedDb),
        returnValue: _i7.Future<_i3.Database>.value(_FakeDatabase_2(
          this,
          Invocation.getter(#sharedDb),
        )),
      ) as _i7.Future<_i3.Database>);

  @override
  _i7.Future<void> savePosition({
    required String? bookPath,
    required int? chapterIndex,
    required Duration? position,
    required int? globalPositionMs,
    required int? totalDurationMs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePosition,
          [],
          {
            #bookPath: bookPath,
            #chapterIndex: chapterIndex,
            #position: position,
            #globalPositionMs: globalPositionMs,
            #totalDurationMs: totalDurationMs,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> repairFromGlobal(_i9.Audiobook? book) => (super.noSuchMethod(
        Invocation.method(
          #repairFromGlobal,
          [book],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<({int chapterIndex, Duration position})?> getPosition(
          String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [bookPath],
        ),
        returnValue:
            _i7.Future<({int chapterIndex, Duration position})?>.value(),
      ) as _i7.Future<({int chapterIndex, Duration position})?>);

  @override
  _i7.Future<void> setBookStatus(
    String? bookPath,
    _i9.BookStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBookStatus,
          [
            bookPath,
            status,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateBookStatus(
    String? bookPath,
    _i9.BookStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookStatus,
          [
            bookPath,
            status,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i9.BookStatus> getBookStatus(String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookStatus,
          [bookPath],
        ),
        returnValue:
            _i7.Future<_i9.BookStatus>.value(_i9.BookStatus.notStarted),
      ) as _i7.Future<_i9.BookStatus>);

  @override
  _i7.Future<Map<String, _i9.BookStatus>> getAllStatuses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllStatuses,
          [],
        ),
        returnValue: _i7.Future<Map<String, _i9.BookStatus>>.value(
            <String, _i9.BookStatus>{}),
      ) as _i7.Future<Map<String, _i9.BookStatus>>);

  @override
  _i7.Future<_i4.Bookmark> addBookmark(_i4.Bookmark? bookmark) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBookmark,
          [bookmark],
        ),
        returnValue: _i7.Future<_i4.Bookmark>.value(_FakeBookmark_3(
          this,
          Invocation.method(
            #addBookmark,
            [bookmark],
          ),
        )),
      ) as _i7.Future<_i4.Bookmark>);

  @override
  _i7.Future<List<_i4.Bookmark>> getBookmarks(String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarks,
          [bookPath],
        ),
        returnValue: _i7.Future<List<_i4.Bookmark>>.value(<_i4.Bookmark>[]),
      ) as _i7.Future<List<_i4.Bookmark>>);

  @override
  _i7.Future<void> deleteBookmark(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBookmark,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateBookmark(
    int? id, {
    required String? label,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookmark,
          [id],
          {
            #label: label,
            #notes: notes,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getLastPlayedBookPath() => (super.noSuchMethod(
        Invocation.method(
          #getLastPlayedBookPath,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<
      List<
          ({
            String bookPath,
            int chapterIndex,
            int globalPositionMs,
            int positionMs,
            int totalDurationMs,
            int updatedAt
          })>> getAllPositions() => (super.noSuchMethod(
        Invocation.method(
          #getAllPositions,
          [],
        ),
        returnValue: _i7.Future<
            List<
                ({
                  String bookPath,
                  int chapterIndex,
                  int globalPositionMs,
                  int positionMs,
                  int totalDurationMs,
                  int updatedAt
                })>>.value(<({
          String bookPath,
          int chapterIndex,
          int globalPositionMs,
          int positionMs,
          int totalDurationMs,
          int updatedAt
        })>[]),
      ) as _i7.Future<
          List<
              ({
                String bookPath,
                int chapterIndex,
                int globalPositionMs,
                int positionMs,
                int totalDurationMs,
                int updatedAt
              })>>);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i5.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.SettingsSnapshot> getSettingsSnapshot() => (super.noSuchMethod(
        Invocation.method(
          #getSettingsSnapshot,
          [],
        ),
        returnValue:
            _i7.Future<_i5.SettingsSnapshot>.value(_FakeSettingsSnapshot_4(
          this,
          Invocation.method(
            #getSettingsSnapshot,
            [],
          ),
        )),
      ) as _i7.Future<_i5.SettingsSnapshot>);

  @override
  _i7.Future<String?> getLibraryPath() => (super.noSuchMethod(
        Invocation.method(
          #getLibraryPath,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> setLibraryPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #setLibraryPath,
          [path],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearLibraryPath() => (super.noSuchMethod(
        Invocation.method(
          #clearLibraryPath,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool?> getAnalyticsConsent() => (super.noSuchMethod(
        Invocation.method(
          #getAnalyticsConsent,
          [],
        ),
        returnValue: _i7.Future<bool?>.value(),
      ) as _i7.Future<bool?>);

  @override
  _i7.Future<void> setAnalyticsConsent(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticsConsent,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> setThemeMode(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> getMetadataEnrichment() => (super.noSuchMethod(
        Invocation.method(
          #getMetadataEnrichment,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> setMetadataEnrichment(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setMetadataEnrichment,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> getAutoRewind() => (super.noSuchMethod(
        Invocation.method(
          #getAutoRewind,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> setAutoRewind(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoRewind,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> getSkipInterval() => (super.noSuchMethod(
        Invocation.method(
          #getSkipInterval,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> setSkipInterval(int? seconds) => (super.noSuchMethod(
        Invocation.method(
          #setSkipInterval,
          [seconds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getLibrarySort() => (super.noSuchMethod(
        Invocation.method(
          #getLibrarySort,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> setLibrarySort(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setLibrarySort,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<({String id, bool isShared, String name})?> getDriveRootFolder() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriveRootFolder,
          [],
        ),
        returnValue:
            _i7.Future<({String id, bool isShared, String name})?>.value(),
      ) as _i7.Future<({String id, bool isShared, String name})?>);

  @override
  _i7.Future<void> setDriveRootFolder(
    String? id,
    String? name, {
    bool? isShared = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDriveRootFolder,
          [
            id,
            name,
          ],
          {#isShared: isShared},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearDriveRootFolder() => (super.noSuchMethod(
        Invocation.method(
          #clearDriveRootFolder,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> getRemoveWhenFinished() => (super.noSuchMethod(
        Invocation.method(
          #getRemoveWhenFinished,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> setRemoveWhenFinished(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setRemoveWhenFinished,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> getRefreshOnStartup() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshOnStartup,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> setRefreshOnStartup(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setRefreshOnStartup,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> getDriveProgressSync() => (super.noSuchMethod(
        Invocation.method(
          #getDriveProgressSync,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> setDriveProgressSync(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDriveProgressSync,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<({String id, String name})?> getDriveBackupFolder() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriveBackupFolder,
          [],
        ),
        returnValue: _i7.Future<({String id, String name})?>.value(),
      ) as _i7.Future<({String id, String name})?>);

  @override
  _i7.Future<void> setDriveBackupFolder(
    String? id,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDriveBackupFolder,
          [
            id,
            name,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearDriveBackupFolder() => (super.noSuchMethod(
        Invocation.method(
          #clearDriveBackupFolder,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i14.AvailabilityFilterState> getAvailabilityFilter() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailabilityFilter,
          [],
        ),
        returnValue: _i7.Future<_i14.AvailabilityFilterState>.value(
            _i14.AvailabilityFilterState.all),
      ) as _i7.Future<_i14.AvailabilityFilterState>);

  @override
  _i7.Future<void> setAvailabilityFilter(_i14.AvailabilityFilterState? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAvailabilityFilter,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> getViewMode() => (super.noSuchMethod(
        Invocation.method(
          #getViewMode,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getViewMode,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> setViewMode(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setViewMode,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [ScannerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScannerService extends _i1.Mock implements _i15.ScannerService {
  MockScannerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i9.Audiobook>> scanFolder(
    String? folderPath, {
    Set<String>? excludePaths = const {},
    void Function(_i9.Audiobook)? onBookFound,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanFolder,
          [folderPath],
          {
            #excludePaths: excludePaths,
            #onBookFound: onBookFound,
          },
        ),
        returnValue: _i7.Future<List<_i9.Audiobook>>.value(<_i9.Audiobook>[]),
      ) as _i7.Future<List<_i9.Audiobook>>);

  @override
  _i7.Future<_i9.Audiobook?> scanSingleBook(String? bookDirPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanSingleBook,
          [bookDirPath],
        ),
        returnValue: _i7.Future<_i9.Audiobook?>.value(),
      ) as _i7.Future<_i9.Audiobook?>);
}

/// A class which mocks [SleepTimerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSleepTimerController extends _i1.Mock
    implements _i16.SleepTimerController {
  MockSleepTimerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<Duration?> get remaining => (super.noSuchMethod(
        Invocation.getter(#remaining),
        returnValue: _FakeValueNotifier_1<Duration?>(
          this,
          Invocation.getter(#remaining),
        ),
      ) as _i2.ValueNotifier<Duration?>);

  @override
  _i2.ValueNotifier<bool> get stopAtChapterEnd => (super.noSuchMethod(
        Invocation.getter(#stopAtChapterEnd),
        returnValue: _FakeValueNotifier_1<bool>(
          this,
          Invocation.getter(#stopAtChapterEnd),
        ),
      ) as _i2.ValueNotifier<bool>);

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  void startTimed(
    Duration? duration, {
    required _i17.VoidCallback? onFire,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #startTimed,
          [duration],
          {#onFire: onFire},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStopAtChapterEnd(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setStopAtChapterEnd,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cancel() => super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disposeForTesting() => super.noSuchMethod(
        Invocation.method(
          #disposeForTesting,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
